#!/usr/bin/env python3
"""Emit `assets/plots/full_width_vs_pca_table.tex`.

Reads `data/cosmos_1024.parquet` (PCA-1024 singles) and
`data/full_width_per_seed.parquet` (raw full-width singles, computed by
`scripts/compare_pca_vs_fullwidth.py`), and renders a two-panel LaTeX
table (one per COSMOS-Web modality) with per-model R² mean±std for each
representation. Std is shown at 1 significant figure, mean at matching
precision.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd  # pyright: ignore[reportMissingImports]

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "data"
FIGS = REPO / "assets" / "plots"
OUT_TEX = FIGS / "full_width_vs_pca_table.tex"

MODALITIES = ["hsc", "jwst"]
PROPERTIES = ["redshift", "mass", "sSFR"]
PROPERTY_LABEL = {"redshift": r"$z$", "mass": r"$\log M_\star$", "sSFR": "sSFR"}
MODALITY_LABEL = {"hsc": "HSC", "jwst": "JWST"}
MODEL_LABELS = {
    "astropt_015M": "AstroPT 15M",
    "astropt_095M": "AstroPT 95M",
    "astropt_850M": "AstroPT 850M",
    "clip_base": "CLIP 86M",
    "clip_large": "CLIP 304M",
    "convnext_nano": "ConvNeXt-V2 15M",
    "convnext_tiny": "ConvNeXt-V2 28M",
    "convnext_base": "ConvNeXt-V2 89M",
    "convnext_large": "ConvNeXt-V2 198M",
    "ijepa_huge": "I-JEPA 632M",
    "ijepa_giant": "I-JEPA 1B",
    "llava_15_7b": "LLaVA-1.5 7B",
    "llava_15_13b": "LLaVA-1.5 13B",
    "vit_base": "ViT 86M",
    "vit_large": "ViT 304M",
    "vit_huge": "ViT 632M",
    "vit-mae_base": "ViT-MAE 86M",
    "vit-mae_large": "ViT-MAE 304M",
    "vit-mae_huge": "ViT-MAE 632M",
    "vjepa_large": "V-JEPA-2 300M",
    "vjepa_huge": "V-JEPA-2 600M",
    "vjepa_giant": "V-JEPA-2 1B",
}


def load_paired() -> pd.DataFrame:
    """Per (modality, model, property, seed): pca R² and full R²."""
    pca_df = pd.read_parquet(DATA / "cosmos_1024.parquet")
    pca_df = pca_df[pca_df.source.str.startswith("single_")].copy()
    pca_df["model"] = pca_df.source.str.removeprefix("single_").str.removesuffix("_pca1024")
    pca_df = pca_df[["modality", "model", "property", "seed", "r2"]].rename(
        columns={"r2": "pca_r2"}
    )

    full_df = pd.read_parquet(DATA / "full_width_per_seed.parquet").rename(
        columns={"r2": "full_r2"}
    )

    paired = pca_df.merge(
        full_df, on=["modality", "model", "property", "seed"], how="inner"
    ).sort_values(["modality", "model", "property", "seed"])
    return paired


def cell_stats(paired: pd.DataFrame, modality: str, model: str, prop: str):
    sub = paired[
        (paired.modality == modality) & (paired.model == model) & (paired.property == prop)
    ]
    pca = sub["pca_r2"].to_numpy()
    full = sub["full_r2"].to_numpy()
    return pca.mean(), pca.std(), full.mean(), full.std()


def fmt_cell(mean: float, std: float, better: bool) -> str:
    """mean ± std, std at 1 significant figure, mean at matching precision."""
    sd1 = float(f"{std:.1g}")
    decimals = min(len(f"{sd1:.10f}".rstrip("0").split(".")[1]), 5)
    body = f"{mean:.{decimals}f}$\\pm${sd1:.{decimals}f}"
    return f"\\textbf{{{body}}}" if better else body


def main() -> None:
    paired = load_paired()
    models = sorted(paired.model.unique())

    lines = [
        "% Auto-generated by scripts/gen_full_width_table.py -- do not edit.",
        "\\begin{table}[htbp]",
        "  \\caption{Per-model linear-probe $R^2$ (mean $\\pm$ std, 10 seeds;",
        "    std at 1 significant figure) on the raw full-width embedding",
        "    vs its PCA-to-1024 projection. Bold marks the higher mean.",
        "    Models with native width at most 1024 still show tiny diffs",
        "    ($\\Delta R^2 \\lesssim 10^{-3}$) from randomized-SVD",
        "    reprojection error.}",
        "  \\label{tab:fullwidth}",
        "  \\centering\\footnotesize",
    ]

    col_spec = "l" + "cc" * len(PROPERTIES)
    for modality in MODALITIES:
        if modality == MODALITIES[0]:
            lines.append(f"  \\begin{{tabular}}{{{col_spec}}}")
            lines.append("    \\toprule")
        else:
            lines.append("    \\midrule")
        lines.append(f"    \\multicolumn{{7}}{{l}}{{\\textbf{{{MODALITY_LABEL[modality]}}}}} \\\\")
        lines.append("    \\midrule")
        prop_headers = " & ".join(
            f"\\multicolumn{{2}}{{c}}{{{PROPERTY_LABEL[p]}}}" for p in PROPERTIES
        )
        sub = " & ".join("pca & full" for _ in PROPERTIES)
        lines.append(f"    model & {prop_headers} \\\\")
        lines.append(f"          & {sub} \\\\")
        lines.append("    \\midrule")

        for model in models:
            cells: list[str] = []
            for prop in PROPERTIES:
                pm, ps, fm, fs = cell_stats(paired, modality, model, prop)
                better_pca = pm > fm
                pca_cell = fmt_cell(mean=pm, std=ps, better=better_pca)
                full_cell = fmt_cell(mean=fm, std=fs, better=not better_pca)
                cells.extend([pca_cell, full_cell])
            lines.append(f"    {MODEL_LABELS[model]} & " + " & ".join(cells) + " \\\\")

    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
    ]

    FIGS.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
