#!/usr/bin/env python3
"""Emit `assets/plots/full_width_vs_pca_table.tex`.

Reads `data/cosmos_1024.parquet` (PCA-1024 singles) and
`data/full_width_per_seed.parquet` (raw full-width singles, computed by
`scripts/compare_pca_vs_fullwidth.py`), and renders a two-panel LaTeX
table (one per COSMOS-Web modality) with per-model R² mean±std for each
representation plus the per-cell paired two-sided Wilcoxon p-value over
the 10 seeds.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "data"
FIGS = REPO / "assets" / "plots"
OUT_TEX = FIGS / "full_width_vs_pca_table.tex"

MODALITIES = ["hsc", "jwst"]
PROPERTIES = ["redshift", "mass", "sSFR"]
PROPERTY_LABEL = {"redshift": r"$z$", "mass": r"$\log M_\star$", "sSFR": "sSFR"}
MODALITY_LABEL = {"hsc": "HSC", "jwst": "JWST"}


def load_paired() -> pd.DataFrame:
    """Per (modality, model, property, seed): pca R² and full R²."""
    pca_df = pd.read_parquet(DATA / "cosmos_1024.parquet")
    pca_df = pca_df[pca_df.source.str.startswith("single_")].copy()
    pca_df["model"] = (
        pca_df.source.str.removeprefix("single_").str.removesuffix("_pca1024")
    )
    pca_df = pca_df[["modality", "model", "property", "seed", "r2"]].rename(
        columns={"r2": "pca_r2"}
    )

    full_df = pd.read_parquet(DATA / "full_width_per_seed.parquet").rename(
        columns={"r2": "full_r2"}
    )

    paired = pca_df.merge(
        full_df, on=["modality", "model", "property", "seed"], how="inner"
    ).sort_values(["modality", "model", "property", "seed"])
    return paired


def cell_stats(paired: pd.DataFrame, modality: str, model: str, prop: str):
    sub = paired[
        (paired.modality == modality)
        & (paired.model == model)
        & (paired.property == prop)
    ]
    pca = sub["pca_r2"].to_numpy()
    full = sub["full_r2"].to_numpy()
    try:
        _, p = wilcoxon(pca, full, alternative="two-sided",
                        zero_method="wilcox")
    except ValueError:  # all differences are zero (native width ≤ 1024)
        p = float("nan")
    return pca.mean(), pca.std(), full.mean(), full.std(), p


def fmt_cell(mean: float, std: float, better: bool) -> str:
    body = f"{mean:.3f}$\\pm$.{int(round(std * 1000)):03d}"
    return f"\\textbf{{{body}}}" if better else body


def main() -> None:
    paired = load_paired()
    models = sorted(paired.model.unique())

    lines = [
        "% Auto-generated by scripts/gen_full_width_table.py -- do not edit.",
        "\\begin{table}[htbp]",
        "  \\caption{Per-model linear-probe $R^2$ (mean $\\pm$ std, 10 seeds)",
        "    on the raw full-width embedding vs its PCA-to-1024 projection.",
        "    Bold marks the higher mean. $p$: paired two-sided Wilcoxon",
        "    between the two representations across seeds. Models with",
        "    native width at most 1024 still show tiny diffs ($\\Delta R^2",
        "    \\lesssim 10^{-3}$) from randomized-SVD reprojection error.",
        "    }",
        "  \\label{tab:fullwidth}",
        "  \\centering\\footnotesize",
    ]

    col_spec = "l" + "ccc" * len(PROPERTIES)
    for modality in MODALITIES:
        if modality == MODALITIES[0]:
            lines.append(f"  \\begin{{tabular}}{{{col_spec}}}")
            lines.append("    \\toprule")
        else:
            lines.append("    \\midrule")
        lines.append(
            f"    \\multicolumn{{10}}{{l}}{{\\textbf{{{MODALITY_LABEL[modality]}}}}} \\\\"
        )
        lines.append("    \\midrule")
        prop_headers = " & ".join(
            f"\\multicolumn{{3}}{{c}}{{{PROPERTY_LABEL[p]}}}" for p in PROPERTIES
        )
        sub = " & ".join("pca & full & $p$" for _ in PROPERTIES)
        lines.append(f"    model & {prop_headers} \\\\")
        lines.append(f"          & {sub} \\\\")
        lines.append("    \\midrule")

        for model in models:
            cells: list[str] = []
            for prop in PROPERTIES:
                pm, ps, fm, fs, p = cell_stats(paired, modality, model, prop)
                better_pca = pm > fm
                pca_cell = fmt_cell(pm, ps, better_pca)
                full_cell = fmt_cell(fm, fs, not better_pca)
                p_str = "---" if np.isnan(p) else f"{p:.3g}"
                cells.extend([pca_cell, full_cell, p_str])
            lines.append(
                f"    \\texttt{{{model.replace('_', '\\_')}}} & " + " & ".join(cells) + " \\\\"
            )

    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
    ]

    FIGS.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
